"""Add user_id to poshts

Revision ID: 0258c56d0e88
Revises:
Create Date: 2025-07-23 13:46:33.118713

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0258c56d0e88"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_poshts")
    op.alter_column("poshts", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("poshts", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_table(
        "_alembic_tmp_poshts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=15), nullable=False),
        sa.Column("posht_text", sa.VARCHAR(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user")),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
