"""Add auto_comment_delay to user

Revision ID: 7f6c64663877
Revises: fd7b21daadb0
Create Date: 2025-07-29 14:06:54.702622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6c64663877'
down_revision: Union[str, None] = 'fd7b21daadb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('poshts', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poshts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
