"""Add is_blocked field to posрts and comments

Revision ID: cc47a3d5c364
Revises: cd983db6e7e5
Create Date: 2025-07-28 10:28:54.506245

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc47a3d5c364"
down_revision: Union[str, None] = "cd983db6e7e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("poshts", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("poshts", "is_blocked")
    op.drop_column("comments", "is_blocked")
    # ### end Alembic commands ###
