"""Add auto_comment_delay to user and auto_created to comment

Revision ID: fd7b21daadb0
Revises: cc47a3d5c364
Create Date: 2025-07-29 14:02:30.118895

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd7b21daadb0"
down_revision: Union[str, None] = "cc47a3d5c364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("users", sa.Column("auto_comment_delay", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auto_comment_delay")
    op.alter_column("poshts", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("comments", "auto_created")
    # ### end Alembic commands ###
